language: python
python:
  - 2.7

sudo: required
dist: trusty

env:
  - ANSIBLE_VERSION=2.1.0.0
  - ANSIBLE_VERSION=2.1.1.0
  - ANSIBLE_VERSION=2.1.2.0
 
before_install:
  - sudo apt-get install -y python-dev libxml2-dev python-pip libxslt1-dev build-essential libssl-dev libffi-dev

install:
  - pip install -r requirements.txt
  - pip install -q ansible==$ANSIBLE_VERSION
  - ansible-galaxy --force install Juniper.junos -p ./

script:
  - ansible-playbook ansible/pb.template.yml --extra-vars "device=Openconfig_Routers template=ansible/openconfig_bgp.j2" --syntax-check
  - ansible-playbook ansible/pb.rollback.yml --extra-vars "device=Openconfig_Routers rbid=1" --syntax-check
  - ansible-playbook ansible/pb.ping.yml --syntax-check
  - ansible-playbook ansible/pb.oc.bgp.yml --syntax-check
  - ansible-playbook ansible/pb.check.physical.topology.yml --syntax-check
  - ansible-playbook ansible/pb.backup.yml --extra-vars "device=Openconfig_Routers" --syntax-check
  - ansible-playbook ansible/pb.config.yml --extra-vars "device=Openconfig_Routers cli=set system login message newbanner" --syntax-check 
  - ansible-playbook ansible/pb.command.yml --extra-vars "device=Openconfig_Routers cli=show version" --syntax-check
 
  
branches:
  only:
   - master

notifications:
  email:
    recipients:
      - khelil.sator.git@gmail.com
    on_failure: always
  slack: 
    ksator-junos:XAUJP6A29mgYtUtGIJQdPBS7
