---
 - name: pass a junos set or delete command
   hosts: "{{ device }}"
   connection: local
   gather_facts: no

   tasks:
   - name: pass a junos set or delete command  
     junos_config:
      provider: "{{ credentials }}"
      lines: "{{ cli }}"
      comment: configured by Ansible playbook pb.config.yml using module junos_config

   - name: Send Slack notification
     local_action:
       module: slack
       #http://docs.ansible.com/ansible/slack_module.html
       username: "pb.config.yml on {{ inventory_hostname }}"
       channel: general
       token: T2MBN64JX/B2N0Z2MEU/1OoB46XLX6Q1oFf89Xl2X9gq
       icon_url: "https://www.ansible.com/hs-fs/hub/330046/file-448313641-png/favicon.png"
       msg: "{{ cli }}"

